# Base image for the runtime
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

# Build image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

# Copy everything from the full repo (because the context is root)
COPY . .

# Move into the server folder and build
WORKDIR /src/server
RUN dotnet build server.csproj -c Release -o /app/build
RUN dotnet publish server.csproj -c Release -o /app/publish

# Final image
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 80
ENTRYPOINT ["dotnet", "server.dll"]


